//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.01.29 at 11:31:28 AM IST 
//


package com.personal.converters;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Extension"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="IconKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IsPlainTextNodeName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IsPlainTextStepInfo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data"
})
@XmlRootElement(name = "ReportNode")
public class ReportNode {

    @XmlElement(name = "Data", required = true)
    protected Data data;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Extension"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="IconKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IsPlainTextNodeName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IsPlainTextStepInfo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "description",
        "startTime",
        "result",
        "extension"
    })
    public static class Data {

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "StartTime", required = true)
        protected String startTime;
        @XmlElement(name = "Result", required = true)
        protected String result;
        @XmlElement(name = "Extension", required = true)
        protected Extension extension;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartTime(String value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the result property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResult() {
            return result;
        }

        /**
         * Sets the value of the result property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResult(String value) {
            this.result = value;
        }

        /**
         * Gets the value of the extension property.
         * 
         * @return
         *     possible object is
         *     {@link Extension }
         *     
         */
        public Extension getExtension() {
            return extension;
        }

        /**
         * Sets the value of the extension property.
         * 
         * @param value
         *     allowed object is
         *     {@link Extension }
         *     
         */
        public void setExtension(Extension value) {
            this.extension = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="IconKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IsPlainTextNodeName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IsPlainTextStepInfo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "iconKey",
            "isPlainTextNodeName",
            "isPlainTextStepInfo"
        })
        public static class Extension {

            @XmlElement(name = "IconKey", required = true)
            protected String iconKey;
            @XmlElement(name = "IsPlainTextNodeName", required = true)
            protected String isPlainTextNodeName;
            @XmlElement(name = "IsPlainTextStepInfo", required = true)
            protected String isPlainTextStepInfo;

            /**
             * Gets the value of the iconKey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIconKey() {
                return iconKey;
            }

            /**
             * Sets the value of the iconKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIconKey(String value) {
                this.iconKey = value;
            }

            /**
             * Gets the value of the isPlainTextNodeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsPlainTextNodeName() {
                return isPlainTextNodeName;
            }

            /**
             * Sets the value of the isPlainTextNodeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsPlainTextNodeName(String value) {
                this.isPlainTextNodeName = value;
            }

            /**
             * Gets the value of the isPlainTextStepInfo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsPlainTextStepInfo() {
                return isPlainTextStepInfo;
            }

            /**
             * Sets the value of the isPlainTextStepInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsPlainTextStepInfo(String value) {
                this.isPlainTextStepInfo = value;
            }

        }

    }

}
